/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_badlogic_jglfw_Glfw */

#ifndef _Included_com_badlogic_jglfw_Glfw
#define _Included_com_badlogic_jglfw_Glfw
#ifdef __cplusplus
extern "C" {
#endif
#undef com_badlogic_jglfw_Glfw_GLFW_RELEASE
#define com_badlogic_jglfw_Glfw_GLFW_RELEASE 0L
#undef com_badlogic_jglfw_Glfw_GLFW_PRESS
#define com_badlogic_jglfw_Glfw_GLFW_PRESS 1L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_UNKNOWN
#define com_badlogic_jglfw_Glfw_GLFW_KEY_UNKNOWN -1L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_SPACE
#define com_badlogic_jglfw_Glfw_GLFW_KEY_SPACE 32L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_SPECIAL
#define com_badlogic_jglfw_Glfw_GLFW_KEY_SPECIAL 256L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_ESC
#define com_badlogic_jglfw_Glfw_GLFW_KEY_ESC 257L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_F1
#define com_badlogic_jglfw_Glfw_GLFW_KEY_F1 258L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_F2
#define com_badlogic_jglfw_Glfw_GLFW_KEY_F2 259L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_F3
#define com_badlogic_jglfw_Glfw_GLFW_KEY_F3 260L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_F4
#define com_badlogic_jglfw_Glfw_GLFW_KEY_F4 261L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_F5
#define com_badlogic_jglfw_Glfw_GLFW_KEY_F5 262L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_F6
#define com_badlogic_jglfw_Glfw_GLFW_KEY_F6 263L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_F7
#define com_badlogic_jglfw_Glfw_GLFW_KEY_F7 264L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_F8
#define com_badlogic_jglfw_Glfw_GLFW_KEY_F8 265L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_F9
#define com_badlogic_jglfw_Glfw_GLFW_KEY_F9 266L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_F10
#define com_badlogic_jglfw_Glfw_GLFW_KEY_F10 267L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_F11
#define com_badlogic_jglfw_Glfw_GLFW_KEY_F11 268L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_F12
#define com_badlogic_jglfw_Glfw_GLFW_KEY_F12 269L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_F13
#define com_badlogic_jglfw_Glfw_GLFW_KEY_F13 270L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_F14
#define com_badlogic_jglfw_Glfw_GLFW_KEY_F14 271L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_F15
#define com_badlogic_jglfw_Glfw_GLFW_KEY_F15 272L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_F16
#define com_badlogic_jglfw_Glfw_GLFW_KEY_F16 273L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_F17
#define com_badlogic_jglfw_Glfw_GLFW_KEY_F17 274L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_F18
#define com_badlogic_jglfw_Glfw_GLFW_KEY_F18 275L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_F19
#define com_badlogic_jglfw_Glfw_GLFW_KEY_F19 276L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_F20
#define com_badlogic_jglfw_Glfw_GLFW_KEY_F20 277L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_F21
#define com_badlogic_jglfw_Glfw_GLFW_KEY_F21 278L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_F22
#define com_badlogic_jglfw_Glfw_GLFW_KEY_F22 279L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_F23
#define com_badlogic_jglfw_Glfw_GLFW_KEY_F23 280L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_F24
#define com_badlogic_jglfw_Glfw_GLFW_KEY_F24 281L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_F25
#define com_badlogic_jglfw_Glfw_GLFW_KEY_F25 282L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_UP
#define com_badlogic_jglfw_Glfw_GLFW_KEY_UP 283L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_DOWN
#define com_badlogic_jglfw_Glfw_GLFW_KEY_DOWN 284L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_LEFT
#define com_badlogic_jglfw_Glfw_GLFW_KEY_LEFT 285L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_RIGHT
#define com_badlogic_jglfw_Glfw_GLFW_KEY_RIGHT 286L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_LSHIFT
#define com_badlogic_jglfw_Glfw_GLFW_KEY_LSHIFT 287L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_RSHIFT
#define com_badlogic_jglfw_Glfw_GLFW_KEY_RSHIFT 288L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_LCTRL
#define com_badlogic_jglfw_Glfw_GLFW_KEY_LCTRL 289L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_RCTRL
#define com_badlogic_jglfw_Glfw_GLFW_KEY_RCTRL 290L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_LALT
#define com_badlogic_jglfw_Glfw_GLFW_KEY_LALT 291L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_RALT
#define com_badlogic_jglfw_Glfw_GLFW_KEY_RALT 292L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_TAB
#define com_badlogic_jglfw_Glfw_GLFW_KEY_TAB 293L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_ENTER
#define com_badlogic_jglfw_Glfw_GLFW_KEY_ENTER 294L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_BACKSPACE
#define com_badlogic_jglfw_Glfw_GLFW_KEY_BACKSPACE 295L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_INSERT
#define com_badlogic_jglfw_Glfw_GLFW_KEY_INSERT 296L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_DEL
#define com_badlogic_jglfw_Glfw_GLFW_KEY_DEL 297L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_PAGEUP
#define com_badlogic_jglfw_Glfw_GLFW_KEY_PAGEUP 298L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_PAGEDOWN
#define com_badlogic_jglfw_Glfw_GLFW_KEY_PAGEDOWN 299L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_HOME
#define com_badlogic_jglfw_Glfw_GLFW_KEY_HOME 300L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_END
#define com_badlogic_jglfw_Glfw_GLFW_KEY_END 301L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_KP_0
#define com_badlogic_jglfw_Glfw_GLFW_KEY_KP_0 302L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_KP_1
#define com_badlogic_jglfw_Glfw_GLFW_KEY_KP_1 303L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_KP_2
#define com_badlogic_jglfw_Glfw_GLFW_KEY_KP_2 304L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_KP_3
#define com_badlogic_jglfw_Glfw_GLFW_KEY_KP_3 305L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_KP_4
#define com_badlogic_jglfw_Glfw_GLFW_KEY_KP_4 306L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_KP_5
#define com_badlogic_jglfw_Glfw_GLFW_KEY_KP_5 307L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_KP_6
#define com_badlogic_jglfw_Glfw_GLFW_KEY_KP_6 308L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_KP_7
#define com_badlogic_jglfw_Glfw_GLFW_KEY_KP_7 309L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_KP_8
#define com_badlogic_jglfw_Glfw_GLFW_KEY_KP_8 310L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_KP_9
#define com_badlogic_jglfw_Glfw_GLFW_KEY_KP_9 311L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_KP_DIVIDE
#define com_badlogic_jglfw_Glfw_GLFW_KEY_KP_DIVIDE 312L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_KP_MULTIPLY
#define com_badlogic_jglfw_Glfw_GLFW_KEY_KP_MULTIPLY 313L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_KP_SUBTRACT
#define com_badlogic_jglfw_Glfw_GLFW_KEY_KP_SUBTRACT 314L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_KP_ADD
#define com_badlogic_jglfw_Glfw_GLFW_KEY_KP_ADD 315L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_KP_DECIMAL
#define com_badlogic_jglfw_Glfw_GLFW_KEY_KP_DECIMAL 316L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_KP_EQUAL
#define com_badlogic_jglfw_Glfw_GLFW_KEY_KP_EQUAL 317L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_KP_ENTER
#define com_badlogic_jglfw_Glfw_GLFW_KEY_KP_ENTER 318L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_KP_NUM_LOCK
#define com_badlogic_jglfw_Glfw_GLFW_KEY_KP_NUM_LOCK 319L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_CAPS_LOCK
#define com_badlogic_jglfw_Glfw_GLFW_KEY_CAPS_LOCK 320L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_SCROLL_LOCK
#define com_badlogic_jglfw_Glfw_GLFW_KEY_SCROLL_LOCK 321L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_PAUSE
#define com_badlogic_jglfw_Glfw_GLFW_KEY_PAUSE 322L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_LSUPER
#define com_badlogic_jglfw_Glfw_GLFW_KEY_LSUPER 323L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_RSUPER
#define com_badlogic_jglfw_Glfw_GLFW_KEY_RSUPER 324L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_MENU
#define com_badlogic_jglfw_Glfw_GLFW_KEY_MENU 325L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_LAST
#define com_badlogic_jglfw_Glfw_GLFW_KEY_LAST 325L
#undef com_badlogic_jglfw_Glfw_GLFW_MOUSE_BUTTON_1
#define com_badlogic_jglfw_Glfw_GLFW_MOUSE_BUTTON_1 0L
#undef com_badlogic_jglfw_Glfw_GLFW_MOUSE_BUTTON_2
#define com_badlogic_jglfw_Glfw_GLFW_MOUSE_BUTTON_2 1L
#undef com_badlogic_jglfw_Glfw_GLFW_MOUSE_BUTTON_3
#define com_badlogic_jglfw_Glfw_GLFW_MOUSE_BUTTON_3 2L
#undef com_badlogic_jglfw_Glfw_GLFW_MOUSE_BUTTON_4
#define com_badlogic_jglfw_Glfw_GLFW_MOUSE_BUTTON_4 3L
#undef com_badlogic_jglfw_Glfw_GLFW_MOUSE_BUTTON_5
#define com_badlogic_jglfw_Glfw_GLFW_MOUSE_BUTTON_5 4L
#undef com_badlogic_jglfw_Glfw_GLFW_MOUSE_BUTTON_6
#define com_badlogic_jglfw_Glfw_GLFW_MOUSE_BUTTON_6 5L
#undef com_badlogic_jglfw_Glfw_GLFW_MOUSE_BUTTON_7
#define com_badlogic_jglfw_Glfw_GLFW_MOUSE_BUTTON_7 6L
#undef com_badlogic_jglfw_Glfw_GLFW_MOUSE_BUTTON_8
#define com_badlogic_jglfw_Glfw_GLFW_MOUSE_BUTTON_8 7L
#undef com_badlogic_jglfw_Glfw_GLFW_MOUSE_BUTTON_LAST
#define com_badlogic_jglfw_Glfw_GLFW_MOUSE_BUTTON_LAST 7L
#undef com_badlogic_jglfw_Glfw_GLFW_MOUSE_BUTTON_LEFT
#define com_badlogic_jglfw_Glfw_GLFW_MOUSE_BUTTON_LEFT 0L
#undef com_badlogic_jglfw_Glfw_GLFW_MOUSE_BUTTON_RIGHT
#define com_badlogic_jglfw_Glfw_GLFW_MOUSE_BUTTON_RIGHT 1L
#undef com_badlogic_jglfw_Glfw_GLFW_MOUSE_BUTTON_MIDDLE
#define com_badlogic_jglfw_Glfw_GLFW_MOUSE_BUTTON_MIDDLE 2L
#undef com_badlogic_jglfw_Glfw_GLFW_JOYSTICK_1
#define com_badlogic_jglfw_Glfw_GLFW_JOYSTICK_1 0L
#undef com_badlogic_jglfw_Glfw_GLFW_JOYSTICK_2
#define com_badlogic_jglfw_Glfw_GLFW_JOYSTICK_2 1L
#undef com_badlogic_jglfw_Glfw_GLFW_JOYSTICK_3
#define com_badlogic_jglfw_Glfw_GLFW_JOYSTICK_3 2L
#undef com_badlogic_jglfw_Glfw_GLFW_JOYSTICK_4
#define com_badlogic_jglfw_Glfw_GLFW_JOYSTICK_4 3L
#undef com_badlogic_jglfw_Glfw_GLFW_JOYSTICK_5
#define com_badlogic_jglfw_Glfw_GLFW_JOYSTICK_5 4L
#undef com_badlogic_jglfw_Glfw_GLFW_JOYSTICK_6
#define com_badlogic_jglfw_Glfw_GLFW_JOYSTICK_6 5L
#undef com_badlogic_jglfw_Glfw_GLFW_JOYSTICK_7
#define com_badlogic_jglfw_Glfw_GLFW_JOYSTICK_7 6L
#undef com_badlogic_jglfw_Glfw_GLFW_JOYSTICK_8
#define com_badlogic_jglfw_Glfw_GLFW_JOYSTICK_8 7L
#undef com_badlogic_jglfw_Glfw_GLFW_JOYSTICK_9
#define com_badlogic_jglfw_Glfw_GLFW_JOYSTICK_9 8L
#undef com_badlogic_jglfw_Glfw_GLFW_JOYSTICK_10
#define com_badlogic_jglfw_Glfw_GLFW_JOYSTICK_10 9L
#undef com_badlogic_jglfw_Glfw_GLFW_JOYSTICK_11
#define com_badlogic_jglfw_Glfw_GLFW_JOYSTICK_11 10L
#undef com_badlogic_jglfw_Glfw_GLFW_JOYSTICK_12
#define com_badlogic_jglfw_Glfw_GLFW_JOYSTICK_12 11L
#undef com_badlogic_jglfw_Glfw_GLFW_JOYSTICK_13
#define com_badlogic_jglfw_Glfw_GLFW_JOYSTICK_13 12L
#undef com_badlogic_jglfw_Glfw_GLFW_JOYSTICK_14
#define com_badlogic_jglfw_Glfw_GLFW_JOYSTICK_14 13L
#undef com_badlogic_jglfw_Glfw_GLFW_JOYSTICK_15
#define com_badlogic_jglfw_Glfw_GLFW_JOYSTICK_15 14L
#undef com_badlogic_jglfw_Glfw_GLFW_JOYSTICK_16
#define com_badlogic_jglfw_Glfw_GLFW_JOYSTICK_16 15L
#undef com_badlogic_jglfw_Glfw_GLFW_JOYSTICK_LAST
#define com_badlogic_jglfw_Glfw_GLFW_JOYSTICK_LAST 15L
#undef com_badlogic_jglfw_Glfw_GLFW_WINDOW
#define com_badlogic_jglfw_Glfw_GLFW_WINDOW 65537L
#undef com_badlogic_jglfw_Glfw_GLFW_FULLSCREEN
#define com_badlogic_jglfw_Glfw_GLFW_FULLSCREEN 65538L
#undef com_badlogic_jglfw_Glfw_GLFW_OPENED
#define com_badlogic_jglfw_Glfw_GLFW_OPENED 131073L
#undef com_badlogic_jglfw_Glfw_GLFW_ACTIVE
#define com_badlogic_jglfw_Glfw_GLFW_ACTIVE 131074L
#undef com_badlogic_jglfw_Glfw_GLFW_ICONIFIED
#define com_badlogic_jglfw_Glfw_GLFW_ICONIFIED 131075L
#undef com_badlogic_jglfw_Glfw_GLFW_ACCELERATED
#define com_badlogic_jglfw_Glfw_GLFW_ACCELERATED 131076L
#undef com_badlogic_jglfw_Glfw_GLFW_RED_BITS
#define com_badlogic_jglfw_Glfw_GLFW_RED_BITS 131077L
#undef com_badlogic_jglfw_Glfw_GLFW_GREEN_BITS
#define com_badlogic_jglfw_Glfw_GLFW_GREEN_BITS 131078L
#undef com_badlogic_jglfw_Glfw_GLFW_BLUE_BITS
#define com_badlogic_jglfw_Glfw_GLFW_BLUE_BITS 131079L
#undef com_badlogic_jglfw_Glfw_GLFW_ALPHA_BITS
#define com_badlogic_jglfw_Glfw_GLFW_ALPHA_BITS 131080L
#undef com_badlogic_jglfw_Glfw_GLFW_DEPTH_BITS
#define com_badlogic_jglfw_Glfw_GLFW_DEPTH_BITS 131081L
#undef com_badlogic_jglfw_Glfw_GLFW_STENCIL_BITS
#define com_badlogic_jglfw_Glfw_GLFW_STENCIL_BITS 131082L
#undef com_badlogic_jglfw_Glfw_GLFW_REFRESH_RATE
#define com_badlogic_jglfw_Glfw_GLFW_REFRESH_RATE 131083L
#undef com_badlogic_jglfw_Glfw_GLFW_ACCUM_RED_BITS
#define com_badlogic_jglfw_Glfw_GLFW_ACCUM_RED_BITS 131084L
#undef com_badlogic_jglfw_Glfw_GLFW_ACCUM_GREEN_BITS
#define com_badlogic_jglfw_Glfw_GLFW_ACCUM_GREEN_BITS 131085L
#undef com_badlogic_jglfw_Glfw_GLFW_ACCUM_BLUE_BITS
#define com_badlogic_jglfw_Glfw_GLFW_ACCUM_BLUE_BITS 131086L
#undef com_badlogic_jglfw_Glfw_GLFW_ACCUM_ALPHA_BITS
#define com_badlogic_jglfw_Glfw_GLFW_ACCUM_ALPHA_BITS 131087L
#undef com_badlogic_jglfw_Glfw_GLFW_AUX_BUFFERS
#define com_badlogic_jglfw_Glfw_GLFW_AUX_BUFFERS 131088L
#undef com_badlogic_jglfw_Glfw_GLFW_STEREO
#define com_badlogic_jglfw_Glfw_GLFW_STEREO 131089L
#undef com_badlogic_jglfw_Glfw_GLFW_WINDOW_NO_RESIZE
#define com_badlogic_jglfw_Glfw_GLFW_WINDOW_NO_RESIZE 131090L
#undef com_badlogic_jglfw_Glfw_GLFW_FSAA_SAMPLES
#define com_badlogic_jglfw_Glfw_GLFW_FSAA_SAMPLES 131091L
#undef com_badlogic_jglfw_Glfw_GLFW_OPENGL_VERSION_MAJOR
#define com_badlogic_jglfw_Glfw_GLFW_OPENGL_VERSION_MAJOR 131092L
#undef com_badlogic_jglfw_Glfw_GLFW_OPENGL_VERSION_MINOR
#define com_badlogic_jglfw_Glfw_GLFW_OPENGL_VERSION_MINOR 131093L
#undef com_badlogic_jglfw_Glfw_GLFW_OPENGL_FORWARD_COMPAT
#define com_badlogic_jglfw_Glfw_GLFW_OPENGL_FORWARD_COMPAT 131094L
#undef com_badlogic_jglfw_Glfw_GLFW_OPENGL_DEBUG_CONTEXT
#define com_badlogic_jglfw_Glfw_GLFW_OPENGL_DEBUG_CONTEXT 131095L
#undef com_badlogic_jglfw_Glfw_GLFW_OPENGL_PROFILE
#define com_badlogic_jglfw_Glfw_GLFW_OPENGL_PROFILE 131096L
#undef com_badlogic_jglfw_Glfw_GLFW_OPENGL_CORE_PROFILE
#define com_badlogic_jglfw_Glfw_GLFW_OPENGL_CORE_PROFILE 327681L
#undef com_badlogic_jglfw_Glfw_GLFW_OPENGL_COMPAT_PROFILE
#define com_badlogic_jglfw_Glfw_GLFW_OPENGL_COMPAT_PROFILE 327682L
#undef com_badlogic_jglfw_Glfw_GLFW_MOUSE_CURSOR
#define com_badlogic_jglfw_Glfw_GLFW_MOUSE_CURSOR 196609L
#undef com_badlogic_jglfw_Glfw_GLFW_STICKY_KEYS
#define com_badlogic_jglfw_Glfw_GLFW_STICKY_KEYS 196610L
#undef com_badlogic_jglfw_Glfw_GLFW_STICKY_MOUSE_BUTTONS
#define com_badlogic_jglfw_Glfw_GLFW_STICKY_MOUSE_BUTTONS 196611L
#undef com_badlogic_jglfw_Glfw_GLFW_SYSTEM_KEYS
#define com_badlogic_jglfw_Glfw_GLFW_SYSTEM_KEYS 196612L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_REPEAT
#define com_badlogic_jglfw_Glfw_GLFW_KEY_REPEAT 196613L
#undef com_badlogic_jglfw_Glfw_GLFW_AUTO_POLL_EVENTS
#define com_badlogic_jglfw_Glfw_GLFW_AUTO_POLL_EVENTS 196614L
#undef com_badlogic_jglfw_Glfw_GLFW_WAIT
#define com_badlogic_jglfw_Glfw_GLFW_WAIT 262145L
#undef com_badlogic_jglfw_Glfw_GLFW_NOWAIT
#define com_badlogic_jglfw_Glfw_GLFW_NOWAIT 262146L
#undef com_badlogic_jglfw_Glfw_GLFW_PRESENT
#define com_badlogic_jglfw_Glfw_GLFW_PRESENT 327681L
#undef com_badlogic_jglfw_Glfw_GLFW_AXES
#define com_badlogic_jglfw_Glfw_GLFW_AXES 327682L
#undef com_badlogic_jglfw_Glfw_GLFW_BUTTONS
#define com_badlogic_jglfw_Glfw_GLFW_BUTTONS 327683L
#undef com_badlogic_jglfw_Glfw_GLFW_NO_RESCALE_BIT
#define com_badlogic_jglfw_Glfw_GLFW_NO_RESCALE_BIT 1L
#undef com_badlogic_jglfw_Glfw_GLFW_ORIGIN_UL_BIT
#define com_badlogic_jglfw_Glfw_GLFW_ORIGIN_UL_BIT 2L
#undef com_badlogic_jglfw_Glfw_GLFW_BUILD_MIPMAPS_BIT
#define com_badlogic_jglfw_Glfw_GLFW_BUILD_MIPMAPS_BIT 4L
#undef com_badlogic_jglfw_Glfw_GLFW_ALPHA_MAP_BIT
#define com_badlogic_jglfw_Glfw_GLFW_ALPHA_MAP_BIT 8L
#undef com_badlogic_jglfw_Glfw_GLFW_INFINITY
#define com_badlogic_jglfw_Glfw_GLFW_INFINITY 100000.0
/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwInit
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_badlogic_jglfw_Glfw_glfwInit
  (JNIEnv *, jclass);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwTerminate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_Glfw_glfwTerminate
  (JNIEnv *, jclass);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwGetVersionJni
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_Glfw_glfwGetVersionJni
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwOpenWindow
 * Signature: (IIIIIIIII)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_Glfw_glfwOpenWindow
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwOpenWindowHint
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_Glfw_glfwOpenWindowHint
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwCloseWindow
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_Glfw_glfwCloseWindow
  (JNIEnv *, jclass);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwSetWindowTitle
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_Glfw_glfwSetWindowTitle
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwSetWindowSize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_Glfw_glfwSetWindowSize
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwSetWindowPos
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_Glfw_glfwSetWindowPos
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwGetWindowSizeWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_badlogic_jglfw_Glfw_glfwGetWindowSizeWidth
  (JNIEnv *, jclass);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwGetWindowSizeHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_badlogic_jglfw_Glfw_glfwGetWindowSizeHeight
  (JNIEnv *, jclass);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwIconifyWindow
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_Glfw_glfwIconifyWindow
  (JNIEnv *, jclass);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwRestoreWindow
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_Glfw_glfwRestoreWindow
  (JNIEnv *, jclass);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwGetWindowParam
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_badlogic_jglfw_Glfw_glfwGetWindowParam
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwSwapBuffers
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_Glfw_glfwSwapBuffers
  (JNIEnv *, jclass);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwSwapInterval
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_Glfw_glfwSwapInterval
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwGetVideoModesJni
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_com_badlogic_jglfw_Glfw_glfwGetVideoModesJni
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwGetDesktopModeJni
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_Glfw_glfwGetDesktopModeJni
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwPollEvents
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_Glfw_glfwPollEvents
  (JNIEnv *, jclass);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwWaitEvents
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_Glfw_glfwWaitEvents
  (JNIEnv *, jclass);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwGetKey
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_badlogic_jglfw_Glfw_glfwGetKey
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwGetMouseButton
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_badlogic_jglfw_Glfw_glfwGetMouseButton
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwGetMousePosX
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_badlogic_jglfw_Glfw_glfwGetMousePosX
  (JNIEnv *, jclass);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwGetMousePosY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_badlogic_jglfw_Glfw_glfwGetMousePosY
  (JNIEnv *, jclass);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwSetMousePos
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_Glfw_glfwSetMousePos
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwGetMouseWheel
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_badlogic_jglfw_Glfw_glfwGetMouseWheel
  (JNIEnv *, jclass);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwSetMouseWheel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_Glfw_glfwSetMouseWheel
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwSetWindowRefreshCallback
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_Glfw_glfwSetWindowRefreshCallback
  (JNIEnv *, jclass);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwSetWindowCloseCallback
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_Glfw_glfwSetWindowCloseCallback
  (JNIEnv *, jclass);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwSetWindowSizeCallback
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_Glfw_glfwSetWindowSizeCallback
  (JNIEnv *, jclass);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwSetKeyCallback
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_Glfw_glfwSetKeyCallback
  (JNIEnv *, jclass);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwSetCharCallback
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_Glfw_glfwSetCharCallback
  (JNIEnv *, jclass);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwSetMouseButtonCallback
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_Glfw_glfwSetMouseButtonCallback
  (JNIEnv *, jclass);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwSetMousePosCallback
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_Glfw_glfwSetMousePosCallback
  (JNIEnv *, jclass);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwSetMouseWheelCallback
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_Glfw_glfwSetMouseWheelCallback
  (JNIEnv *, jclass);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwGetJoystickParam
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_badlogic_jglfw_Glfw_glfwGetJoystickParam
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwGetJoystickPos
 * Signature: (I[F)I
 */
JNIEXPORT jint JNICALL Java_com_badlogic_jglfw_Glfw_glfwGetJoystickPos
  (JNIEnv *, jclass, jint, jfloatArray);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwGetJoystickButtons
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_com_badlogic_jglfw_Glfw_glfwGetJoystickButtons
  (JNIEnv *, jclass, jint, jbyteArray);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwExtensionSupported
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_badlogic_jglfw_Glfw_glfwExtensionSupported
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwEnable
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_Glfw_glfwEnable
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwDisable
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_Glfw_glfwDisable
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
