/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_badlogic_jglfw_gl_GLGenerator */

#ifndef _Included_com_badlogic_jglfw_gl_GLGenerator
#define _Included_com_badlogic_jglfw_gl_GLGenerator
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
