/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_badlogic_jglfw_al_ALC */

#ifndef _Included_com_badlogic_jglfw_al_ALC
#define _Included_com_badlogic_jglfw_al_ALC
#ifdef __cplusplus
extern "C" {
#endif
#undef com_badlogic_jglfw_al_ALC_ALC_INVALID
#define com_badlogic_jglfw_al_ALC_ALC_INVALID 0L
#undef com_badlogic_jglfw_al_ALC_ALC_VERSION_0_1
#define com_badlogic_jglfw_al_ALC_ALC_VERSION_0_1 1L
#undef com_badlogic_jglfw_al_ALC_ALC_FALSE
#define com_badlogic_jglfw_al_ALC_ALC_FALSE 0L
#undef com_badlogic_jglfw_al_ALC_ALC_TRUE
#define com_badlogic_jglfw_al_ALC_ALC_TRUE 1L
#undef com_badlogic_jglfw_al_ALC_ALC_FREQUENCY
#define com_badlogic_jglfw_al_ALC_ALC_FREQUENCY 4103L
#undef com_badlogic_jglfw_al_ALC_ALC_REFRESH
#define com_badlogic_jglfw_al_ALC_ALC_REFRESH 4104L
#undef com_badlogic_jglfw_al_ALC_ALC_SYNC
#define com_badlogic_jglfw_al_ALC_ALC_SYNC 4105L
#undef com_badlogic_jglfw_al_ALC_ALC_MONO_SOURCES
#define com_badlogic_jglfw_al_ALC_ALC_MONO_SOURCES 4112L
#undef com_badlogic_jglfw_al_ALC_ALC_STEREO_SOURCES
#define com_badlogic_jglfw_al_ALC_ALC_STEREO_SOURCES 4113L
#undef com_badlogic_jglfw_al_ALC_ALC_NO_ERROR
#define com_badlogic_jglfw_al_ALC_ALC_NO_ERROR 0L
#undef com_badlogic_jglfw_al_ALC_ALC_INVALID_DEVICE
#define com_badlogic_jglfw_al_ALC_ALC_INVALID_DEVICE 40961L
#undef com_badlogic_jglfw_al_ALC_ALC_INVALID_CONTEXT
#define com_badlogic_jglfw_al_ALC_ALC_INVALID_CONTEXT 40962L
#undef com_badlogic_jglfw_al_ALC_ALC_INVALID_ENUM
#define com_badlogic_jglfw_al_ALC_ALC_INVALID_ENUM 40963L
#undef com_badlogic_jglfw_al_ALC_ALC_INVALID_VALUE
#define com_badlogic_jglfw_al_ALC_ALC_INVALID_VALUE 40964L
#undef com_badlogic_jglfw_al_ALC_ALC_OUT_OF_MEMORY
#define com_badlogic_jglfw_al_ALC_ALC_OUT_OF_MEMORY 40965L
#undef com_badlogic_jglfw_al_ALC_ALC_MAJOR_VERSION
#define com_badlogic_jglfw_al_ALC_ALC_MAJOR_VERSION 4096L
#undef com_badlogic_jglfw_al_ALC_ALC_MINOR_VERSION
#define com_badlogic_jglfw_al_ALC_ALC_MINOR_VERSION 4097L
#undef com_badlogic_jglfw_al_ALC_ALC_ATTRIBUTES_SIZE
#define com_badlogic_jglfw_al_ALC_ALC_ATTRIBUTES_SIZE 4098L
#undef com_badlogic_jglfw_al_ALC_ALC_ALL_ATTRIBUTES
#define com_badlogic_jglfw_al_ALC_ALC_ALL_ATTRIBUTES 4099L
#undef com_badlogic_jglfw_al_ALC_ALC_DEFAULT_DEVICE_SPECIFIER
#define com_badlogic_jglfw_al_ALC_ALC_DEFAULT_DEVICE_SPECIFIER 4100L
#undef com_badlogic_jglfw_al_ALC_ALC_DEVICE_SPECIFIER
#define com_badlogic_jglfw_al_ALC_ALC_DEVICE_SPECIFIER 4101L
#undef com_badlogic_jglfw_al_ALC_ALC_EXTENSIONS
#define com_badlogic_jglfw_al_ALC_ALC_EXTENSIONS 4102L
#undef com_badlogic_jglfw_al_ALC_ALC_EXT_CAPTURE
#define com_badlogic_jglfw_al_ALC_ALC_EXT_CAPTURE 1L
#undef com_badlogic_jglfw_al_ALC_ALC_CAPTURE_DEVICE_SPECIFIER
#define com_badlogic_jglfw_al_ALC_ALC_CAPTURE_DEVICE_SPECIFIER 784L
#undef com_badlogic_jglfw_al_ALC_ALC_CAPTURE_DEFAULT_DEVICE_SPECIFIER
#define com_badlogic_jglfw_al_ALC_ALC_CAPTURE_DEFAULT_DEVICE_SPECIFIER 785L
#undef com_badlogic_jglfw_al_ALC_ALC_CAPTURE_SAMPLES
#define com_badlogic_jglfw_al_ALC_ALC_CAPTURE_SAMPLES 786L
#undef com_badlogic_jglfw_al_ALC_ALC_ENUMERATE_ALL_EXT
#define com_badlogic_jglfw_al_ALC_ALC_ENUMERATE_ALL_EXT 1L
#undef com_badlogic_jglfw_al_ALC_ALC_DEFAULT_ALL_DEVICES_SPECIFIER
#define com_badlogic_jglfw_al_ALC_ALC_DEFAULT_ALL_DEVICES_SPECIFIER 4114L
#undef com_badlogic_jglfw_al_ALC_ALC_ALL_DEVICES_SPECIFIER
#define com_badlogic_jglfw_al_ALC_ALC_ALL_DEVICES_SPECIFIER 4115L
/*
 * Class:     com_badlogic_jglfw_al_ALC
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_ALC_init
  (JNIEnv *, jclass);

/*
 * Class:     com_badlogic_jglfw_al_ALC
 * Method:    alcCreateContext
 * Signature: (J[I)J
 */
JNIEXPORT jlong JNICALL Java_com_badlogic_jglfw_al_ALC_alcCreateContext
  (JNIEnv *, jclass, jlong, jintArray);

/*
 * Class:     com_badlogic_jglfw_al_ALC
 * Method:    alcMakeContextCurrent
 * Signature: (Ljava/nio/Buffer;I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_badlogic_jglfw_al_ALC_alcMakeContextCurrent__Ljava_nio_Buffer_2I
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     com_badlogic_jglfw_al_ALC
 * Method:    alcMakeContextCurrent
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_badlogic_jglfw_al_ALC_alcMakeContextCurrent__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_badlogic_jglfw_al_ALC
 * Method:    alcProcessContext
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_ALC_alcProcessContext__Ljava_nio_Buffer_2I
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     com_badlogic_jglfw_al_ALC
 * Method:    alcProcessContext
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_ALC_alcProcessContext__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_badlogic_jglfw_al_ALC
 * Method:    alcSuspendContext
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_ALC_alcSuspendContext__Ljava_nio_Buffer_2I
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     com_badlogic_jglfw_al_ALC
 * Method:    alcSuspendContext
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_ALC_alcSuspendContext__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_badlogic_jglfw_al_ALC
 * Method:    alcDestroyContext
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_ALC_alcDestroyContext__Ljava_nio_Buffer_2I
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     com_badlogic_jglfw_al_ALC
 * Method:    alcDestroyContext
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_ALC_alcDestroyContext__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_badlogic_jglfw_al_ALC
 * Method:    alcGetCurrentContext
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_badlogic_jglfw_al_ALC_alcGetCurrentContext
  (JNIEnv *, jclass);

/*
 * Class:     com_badlogic_jglfw_al_ALC
 * Method:    alcGetContextsDevice
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_badlogic_jglfw_al_ALC_alcGetContextsDevice
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_badlogic_jglfw_al_ALC
 * Method:    alcOpenDevice
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_badlogic_jglfw_al_ALC_alcOpenDevice
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_badlogic_jglfw_al_ALC
 * Method:    alcCloseDevice
 * Signature: (Ljava/nio/Buffer;I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_badlogic_jglfw_al_ALC_alcCloseDevice__Ljava_nio_Buffer_2I
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     com_badlogic_jglfw_al_ALC
 * Method:    alcCloseDevice
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_badlogic_jglfw_al_ALC_alcCloseDevice__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_badlogic_jglfw_al_ALC
 * Method:    alcGetError
 * Signature: (Ljava/nio/Buffer;I)I
 */
JNIEXPORT jint JNICALL Java_com_badlogic_jglfw_al_ALC_alcGetError__Ljava_nio_Buffer_2I
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     com_badlogic_jglfw_al_ALC
 * Method:    alcGetError
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_badlogic_jglfw_al_ALC_alcGetError__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_badlogic_jglfw_al_ALC
 * Method:    alcIsExtensionPresent
 * Signature: (Ljava/nio/Buffer;ILjava/nio/Buffer;I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_badlogic_jglfw_al_ALC_alcIsExtensionPresent__Ljava_nio_Buffer_2ILjava_nio_Buffer_2I
  (JNIEnv *, jclass, jobject, jint, jobject, jint);

/*
 * Class:     com_badlogic_jglfw_al_ALC
 * Method:    alcIsExtensionPresent
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_badlogic_jglfw_al_ALC_alcIsExtensionPresent__JJ
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_badlogic_jglfw_al_ALC
 * Method:    alcGetEnumValue
 * Signature: (Ljava/nio/Buffer;ILjava/nio/Buffer;I)I
 */
JNIEXPORT jint JNICALL Java_com_badlogic_jglfw_al_ALC_alcGetEnumValue__Ljava_nio_Buffer_2ILjava_nio_Buffer_2I
  (JNIEnv *, jclass, jobject, jint, jobject, jint);

/*
 * Class:     com_badlogic_jglfw_al_ALC
 * Method:    alcGetEnumValue
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_badlogic_jglfw_al_ALC_alcGetEnumValue__JJ
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_badlogic_jglfw_al_ALC
 * Method:    alcGetString
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_badlogic_jglfw_al_ALC_alcGetString
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_badlogic_jglfw_al_ALC
 * Method:    alcGetIntegerv
 * Signature: (Ljava/nio/Buffer;IIILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_ALC_alcGetIntegerv__Ljava_nio_Buffer_2IIILjava_nio_Buffer_2I
  (JNIEnv *, jclass, jobject, jint, jint, jint, jobject, jint);

/*
 * Class:     com_badlogic_jglfw_al_ALC
 * Method:    alcGetIntegerv
 * Signature: (JIIJ)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_ALC_alcGetIntegerv__JIIJ
  (JNIEnv *, jclass, jlong, jint, jint, jlong);

/*
 * Class:     com_badlogic_jglfw_al_ALC
 * Method:    alcCaptureOpenDevice
 * Signature: (Ljava/lang/String;III)J
 */
JNIEXPORT jlong JNICALL Java_com_badlogic_jglfw_al_ALC_alcCaptureOpenDevice
  (JNIEnv *, jclass, jstring, jint, jint, jint);

/*
 * Class:     com_badlogic_jglfw_al_ALC
 * Method:    alcCaptureCloseDevice
 * Signature: (Ljava/nio/Buffer;I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_badlogic_jglfw_al_ALC_alcCaptureCloseDevice__Ljava_nio_Buffer_2I
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     com_badlogic_jglfw_al_ALC
 * Method:    alcCaptureCloseDevice
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_badlogic_jglfw_al_ALC_alcCaptureCloseDevice__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_badlogic_jglfw_al_ALC
 * Method:    alcCaptureStart
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_ALC_alcCaptureStart__Ljava_nio_Buffer_2I
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     com_badlogic_jglfw_al_ALC
 * Method:    alcCaptureStart
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_ALC_alcCaptureStart__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_badlogic_jglfw_al_ALC
 * Method:    alcCaptureStop
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_ALC_alcCaptureStop__Ljava_nio_Buffer_2I
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     com_badlogic_jglfw_al_ALC
 * Method:    alcCaptureStop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_ALC_alcCaptureStop__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_badlogic_jglfw_al_ALC
 * Method:    alcCaptureSamples
 * Signature: (Ljava/nio/Buffer;ILjava/nio/Buffer;II)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_ALC_alcCaptureSamples__Ljava_nio_Buffer_2ILjava_nio_Buffer_2II
  (JNIEnv *, jclass, jobject, jint, jobject, jint, jint);

/*
 * Class:     com_badlogic_jglfw_al_ALC
 * Method:    alcCaptureSamples
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_ALC_alcCaptureSamples__JJI
  (JNIEnv *, jclass, jlong, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
