/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_badlogic_jglfw_al_AL */

#ifndef _Included_com_badlogic_jglfw_al_AL
#define _Included_com_badlogic_jglfw_al_AL
#ifdef __cplusplus
extern "C" {
#endif
#undef com_badlogic_jglfw_al_AL_AL_INVALID
#define com_badlogic_jglfw_al_AL_AL_INVALID -1L
#undef com_badlogic_jglfw_al_AL_AL_INVALID_ENUM
#define com_badlogic_jglfw_al_AL_AL_INVALID_ENUM 40962L
#undef com_badlogic_jglfw_al_AL_AL_INVALID_OPERATION
#define com_badlogic_jglfw_al_AL_AL_INVALID_OPERATION 40964L
#undef com_badlogic_jglfw_al_AL_AL_NONE
#define com_badlogic_jglfw_al_AL_AL_NONE 0L
#undef com_badlogic_jglfw_al_AL_AL_FALSE
#define com_badlogic_jglfw_al_AL_AL_FALSE 0L
#undef com_badlogic_jglfw_al_AL_AL_TRUE
#define com_badlogic_jglfw_al_AL_AL_TRUE 1L
#undef com_badlogic_jglfw_al_AL_AL_SOURCE_RELATIVE
#define com_badlogic_jglfw_al_AL_AL_SOURCE_RELATIVE 514L
#undef com_badlogic_jglfw_al_AL_AL_CONE_INNER_ANGLE
#define com_badlogic_jglfw_al_AL_AL_CONE_INNER_ANGLE 4097L
#undef com_badlogic_jglfw_al_AL_AL_CONE_OUTER_ANGLE
#define com_badlogic_jglfw_al_AL_AL_CONE_OUTER_ANGLE 4098L
#undef com_badlogic_jglfw_al_AL_AL_PITCH
#define com_badlogic_jglfw_al_AL_AL_PITCH 4099L
#undef com_badlogic_jglfw_al_AL_AL_POSITION
#define com_badlogic_jglfw_al_AL_AL_POSITION 4100L
#undef com_badlogic_jglfw_al_AL_AL_DIRECTION
#define com_badlogic_jglfw_al_AL_AL_DIRECTION 4101L
#undef com_badlogic_jglfw_al_AL_AL_VELOCITY
#define com_badlogic_jglfw_al_AL_AL_VELOCITY 4102L
#undef com_badlogic_jglfw_al_AL_AL_LOOPING
#define com_badlogic_jglfw_al_AL_AL_LOOPING 4103L
#undef com_badlogic_jglfw_al_AL_AL_BUFFER
#define com_badlogic_jglfw_al_AL_AL_BUFFER 4105L
#undef com_badlogic_jglfw_al_AL_AL_GAIN
#define com_badlogic_jglfw_al_AL_AL_GAIN 4106L
#undef com_badlogic_jglfw_al_AL_AL_MIN_GAIN
#define com_badlogic_jglfw_al_AL_AL_MIN_GAIN 4109L
#undef com_badlogic_jglfw_al_AL_AL_MAX_GAIN
#define com_badlogic_jglfw_al_AL_AL_MAX_GAIN 4110L
#undef com_badlogic_jglfw_al_AL_AL_ORIENTATION
#define com_badlogic_jglfw_al_AL_AL_ORIENTATION 4111L
#undef com_badlogic_jglfw_al_AL_AL_SOURCE_STATE
#define com_badlogic_jglfw_al_AL_AL_SOURCE_STATE 4112L
#undef com_badlogic_jglfw_al_AL_AL_INITIAL
#define com_badlogic_jglfw_al_AL_AL_INITIAL 4113L
#undef com_badlogic_jglfw_al_AL_AL_PLAYING
#define com_badlogic_jglfw_al_AL_AL_PLAYING 4114L
#undef com_badlogic_jglfw_al_AL_AL_PAUSED
#define com_badlogic_jglfw_al_AL_AL_PAUSED 4115L
#undef com_badlogic_jglfw_al_AL_AL_STOPPED
#define com_badlogic_jglfw_al_AL_AL_STOPPED 4116L
#undef com_badlogic_jglfw_al_AL_AL_BUFFERS_QUEUED
#define com_badlogic_jglfw_al_AL_AL_BUFFERS_QUEUED 4117L
#undef com_badlogic_jglfw_al_AL_AL_BUFFERS_PROCESSED
#define com_badlogic_jglfw_al_AL_AL_BUFFERS_PROCESSED 4118L
#undef com_badlogic_jglfw_al_AL_AL_REFERENCE_DISTANCE
#define com_badlogic_jglfw_al_AL_AL_REFERENCE_DISTANCE 4128L
#undef com_badlogic_jglfw_al_AL_AL_ROLLOFF_FACTOR
#define com_badlogic_jglfw_al_AL_AL_ROLLOFF_FACTOR 4129L
#undef com_badlogic_jglfw_al_AL_AL_CONE_OUTER_GAIN
#define com_badlogic_jglfw_al_AL_AL_CONE_OUTER_GAIN 4130L
#undef com_badlogic_jglfw_al_AL_AL_MAX_DISTANCE
#define com_badlogic_jglfw_al_AL_AL_MAX_DISTANCE 4131L
#undef com_badlogic_jglfw_al_AL_AL_SEC_OFFSET
#define com_badlogic_jglfw_al_AL_AL_SEC_OFFSET 4132L
#undef com_badlogic_jglfw_al_AL_AL_SAMPLE_OFFSET
#define com_badlogic_jglfw_al_AL_AL_SAMPLE_OFFSET 4133L
#undef com_badlogic_jglfw_al_AL_AL_BYTE_OFFSET
#define com_badlogic_jglfw_al_AL_AL_BYTE_OFFSET 4134L
#undef com_badlogic_jglfw_al_AL_AL_SOURCE_TYPE
#define com_badlogic_jglfw_al_AL_AL_SOURCE_TYPE 4135L
#undef com_badlogic_jglfw_al_AL_AL_STATIC
#define com_badlogic_jglfw_al_AL_AL_STATIC 4136L
#undef com_badlogic_jglfw_al_AL_AL_STREAMING
#define com_badlogic_jglfw_al_AL_AL_STREAMING 4137L
#undef com_badlogic_jglfw_al_AL_AL_UNDETERMINED
#define com_badlogic_jglfw_al_AL_AL_UNDETERMINED 4144L
#undef com_badlogic_jglfw_al_AL_AL_FORMAT_MONO8
#define com_badlogic_jglfw_al_AL_AL_FORMAT_MONO8 4352L
#undef com_badlogic_jglfw_al_AL_AL_FORMAT_MONO16
#define com_badlogic_jglfw_al_AL_AL_FORMAT_MONO16 4353L
#undef com_badlogic_jglfw_al_AL_AL_FORMAT_STEREO8
#define com_badlogic_jglfw_al_AL_AL_FORMAT_STEREO8 4354L
#undef com_badlogic_jglfw_al_AL_AL_FORMAT_STEREO16
#define com_badlogic_jglfw_al_AL_AL_FORMAT_STEREO16 4355L
#undef com_badlogic_jglfw_al_AL_AL_FREQUENCY
#define com_badlogic_jglfw_al_AL_AL_FREQUENCY 8193L
#undef com_badlogic_jglfw_al_AL_AL_BITS
#define com_badlogic_jglfw_al_AL_AL_BITS 8194L
#undef com_badlogic_jglfw_al_AL_AL_CHANNELS
#define com_badlogic_jglfw_al_AL_AL_CHANNELS 8195L
#undef com_badlogic_jglfw_al_AL_AL_SIZE
#define com_badlogic_jglfw_al_AL_AL_SIZE 8196L
#undef com_badlogic_jglfw_al_AL_AL_UNUSED
#define com_badlogic_jglfw_al_AL_AL_UNUSED 8208L
#undef com_badlogic_jglfw_al_AL_AL_PENDING
#define com_badlogic_jglfw_al_AL_AL_PENDING 8209L
#undef com_badlogic_jglfw_al_AL_AL_PROCESSED
#define com_badlogic_jglfw_al_AL_AL_PROCESSED 8210L
#undef com_badlogic_jglfw_al_AL_AL_NO_ERROR
#define com_badlogic_jglfw_al_AL_AL_NO_ERROR 0L
#undef com_badlogic_jglfw_al_AL_AL_INVALID_NAME
#define com_badlogic_jglfw_al_AL_AL_INVALID_NAME 40961L
#undef com_badlogic_jglfw_al_AL_AL_ILLEGAL_ENUM
#define com_badlogic_jglfw_al_AL_AL_ILLEGAL_ENUM 40962L
#undef com_badlogic_jglfw_al_AL_AL_INVALID_VALUE
#define com_badlogic_jglfw_al_AL_AL_INVALID_VALUE 40963L
#undef com_badlogic_jglfw_al_AL_AL_ILLEGAL_COMMAND
#define com_badlogic_jglfw_al_AL_AL_ILLEGAL_COMMAND 40964L
#undef com_badlogic_jglfw_al_AL_AL_OUT_OF_MEMORY
#define com_badlogic_jglfw_al_AL_AL_OUT_OF_MEMORY 40965L
#undef com_badlogic_jglfw_al_AL_AL_VENDOR
#define com_badlogic_jglfw_al_AL_AL_VENDOR 45057L
#undef com_badlogic_jglfw_al_AL_AL_VERSION
#define com_badlogic_jglfw_al_AL_AL_VERSION 45058L
#undef com_badlogic_jglfw_al_AL_AL_RENDERER
#define com_badlogic_jglfw_al_AL_AL_RENDERER 45059L
#undef com_badlogic_jglfw_al_AL_AL_EXTENSIONS
#define com_badlogic_jglfw_al_AL_AL_EXTENSIONS 45060L
#undef com_badlogic_jglfw_al_AL_AL_DOPPLER_FACTOR
#define com_badlogic_jglfw_al_AL_AL_DOPPLER_FACTOR 49152L
#undef com_badlogic_jglfw_al_AL_AL_DOPPLER_VELOCITY
#define com_badlogic_jglfw_al_AL_AL_DOPPLER_VELOCITY 49153L
#undef com_badlogic_jglfw_al_AL_AL_SPEED_OF_SOUND
#define com_badlogic_jglfw_al_AL_AL_SPEED_OF_SOUND 49155L
#undef com_badlogic_jglfw_al_AL_AL_DISTANCE_MODEL
#define com_badlogic_jglfw_al_AL_AL_DISTANCE_MODEL 53248L
#undef com_badlogic_jglfw_al_AL_AL_INVERSE_DISTANCE
#define com_badlogic_jglfw_al_AL_AL_INVERSE_DISTANCE 53249L
#undef com_badlogic_jglfw_al_AL_AL_INVERSE_DISTANCE_CLAMPED
#define com_badlogic_jglfw_al_AL_AL_INVERSE_DISTANCE_CLAMPED 53250L
#undef com_badlogic_jglfw_al_AL_AL_LINEAR_DISTANCE
#define com_badlogic_jglfw_al_AL_AL_LINEAR_DISTANCE 53251L
#undef com_badlogic_jglfw_al_AL_AL_LINEAR_DISTANCE_CLAMPED
#define com_badlogic_jglfw_al_AL_AL_LINEAR_DISTANCE_CLAMPED 53252L
#undef com_badlogic_jglfw_al_AL_AL_EXPONENT_DISTANCE
#define com_badlogic_jglfw_al_AL_AL_EXPONENT_DISTANCE 53253L
#undef com_badlogic_jglfw_al_AL_AL_EXPONENT_DISTANCE_CLAMPED
#define com_badlogic_jglfw_al_AL_AL_EXPONENT_DISTANCE_CLAMPED 53254L
/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_init
  (JNIEnv *, jclass);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alDopplerFactor
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alDopplerFactor
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alDopplerVelocity
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alDopplerVelocity
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alSpeedOfSound
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alSpeedOfSound
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alDistanceModel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alDistanceModel
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alEnable
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alEnable
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alDisable
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alDisable
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alIsEnabled
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_badlogic_jglfw_al_AL_alIsEnabled
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alGetString
 * Signature: (I)Ljava/nio/Buffer;
 */
JNIEXPORT jobject JNICALL Java_com_badlogic_jglfw_al_AL_alGetString
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alGetBooleanv
 * Signature: (ILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alGetBooleanv__ILjava_nio_Buffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alGetBooleanv
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alGetBooleanv__IJ
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alGetIntegerv
 * Signature: (ILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alGetIntegerv__ILjava_nio_Buffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alGetIntegerv
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alGetIntegerv__IJ
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alGetFloatv
 * Signature: (ILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alGetFloatv__ILjava_nio_Buffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alGetFloatv
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alGetFloatv__IJ
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alGetDoublev
 * Signature: (ILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alGetDoublev__ILjava_nio_Buffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alGetDoublev
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alGetDoublev__IJ
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alGetBoolean
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_badlogic_jglfw_al_AL_alGetBoolean
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alGetInteger
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_badlogic_jglfw_al_AL_alGetInteger
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alGetFloat
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_com_badlogic_jglfw_al_AL_alGetFloat
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alGetDouble
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_badlogic_jglfw_al_AL_alGetDouble
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alGetError
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_badlogic_jglfw_al_AL_alGetError
  (JNIEnv *, jclass);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alIsExtensionPresent
 * Signature: (Ljava/nio/Buffer;I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_badlogic_jglfw_al_AL_alIsExtensionPresent__Ljava_nio_Buffer_2I
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alIsExtensionPresent
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_badlogic_jglfw_al_AL_alIsExtensionPresent__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alGetEnumValue
 * Signature: (Ljava/nio/Buffer;I)I
 */
JNIEXPORT jint JNICALL Java_com_badlogic_jglfw_al_AL_alGetEnumValue__Ljava_nio_Buffer_2I
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alGetEnumValue
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_badlogic_jglfw_al_AL_alGetEnumValue__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alListenerf
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alListenerf
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alListener3f
 * Signature: (IFFF)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alListener3f
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alListenerfv
 * Signature: (ILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alListenerfv__ILjava_nio_Buffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alListenerfv
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alListenerfv__IJ
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alListeneri
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alListeneri
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alListener3i
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alListener3i
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alListeneriv
 * Signature: (ILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alListeneriv__ILjava_nio_Buffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alListeneriv
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alListeneriv__IJ
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alGetListenerf
 * Signature: (ILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alGetListenerf__ILjava_nio_Buffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alGetListenerf
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alGetListenerf__IJ
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alGetListener3f
 * Signature: (ILjava/nio/Buffer;ILjava/nio/Buffer;ILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alGetListener3f__ILjava_nio_Buffer_2ILjava_nio_Buffer_2ILjava_nio_Buffer_2I
  (JNIEnv *, jclass, jint, jobject, jint, jobject, jint, jobject, jint);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alGetListener3f
 * Signature: (IJJJ)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alGetListener3f__IJJJ
  (JNIEnv *, jclass, jint, jlong, jlong, jlong);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alGetListenerfv
 * Signature: (ILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alGetListenerfv__ILjava_nio_Buffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alGetListenerfv
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alGetListenerfv__IJ
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alGetListeneri
 * Signature: (ILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alGetListeneri__ILjava_nio_Buffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alGetListeneri
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alGetListeneri__IJ
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alGetListener3i
 * Signature: (ILjava/nio/Buffer;ILjava/nio/Buffer;ILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alGetListener3i__ILjava_nio_Buffer_2ILjava_nio_Buffer_2ILjava_nio_Buffer_2I
  (JNIEnv *, jclass, jint, jobject, jint, jobject, jint, jobject, jint);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alGetListener3i
 * Signature: (IJJJ)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alGetListener3i__IJJJ
  (JNIEnv *, jclass, jint, jlong, jlong, jlong);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alGetListeneriv
 * Signature: (ILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alGetListeneriv__ILjava_nio_Buffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alGetListeneriv
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alGetListeneriv__IJ
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alGenSources
 * Signature: (ILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alGenSources__ILjava_nio_Buffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alGenSources
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alGenSources__IJ
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alDeleteSources
 * Signature: (ILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alDeleteSources__ILjava_nio_Buffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alDeleteSources
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alDeleteSources__IJ
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alIsSource
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_badlogic_jglfw_al_AL_alIsSource
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alSourcef
 * Signature: (IIF)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alSourcef
  (JNIEnv *, jclass, jint, jint, jfloat);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alSource3f
 * Signature: (IIFFF)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alSource3f
  (JNIEnv *, jclass, jint, jint, jfloat, jfloat, jfloat);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alSourcefv
 * Signature: (IILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alSourcefv__IILjava_nio_Buffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alSourcefv
 * Signature: (IIJ)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alSourcefv__IIJ
  (JNIEnv *, jclass, jint, jint, jlong);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alSourcei
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alSourcei
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alSource3i
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alSource3i
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alSourceiv
 * Signature: (IILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alSourceiv__IILjava_nio_Buffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alSourceiv
 * Signature: (IIJ)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alSourceiv__IIJ
  (JNIEnv *, jclass, jint, jint, jlong);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alGetSourcef
 * Signature: (IILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alGetSourcef__IILjava_nio_Buffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alGetSourcef
 * Signature: (IIJ)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alGetSourcef__IIJ
  (JNIEnv *, jclass, jint, jint, jlong);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alGetSource3f
 * Signature: (IILjava/nio/Buffer;ILjava/nio/Buffer;ILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alGetSource3f__IILjava_nio_Buffer_2ILjava_nio_Buffer_2ILjava_nio_Buffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint, jobject, jint, jobject, jint);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alGetSource3f
 * Signature: (IIJJJ)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alGetSource3f__IIJJJ
  (JNIEnv *, jclass, jint, jint, jlong, jlong, jlong);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alGetSourcefv
 * Signature: (IILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alGetSourcefv__IILjava_nio_Buffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alGetSourcefv
 * Signature: (IIJ)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alGetSourcefv__IIJ
  (JNIEnv *, jclass, jint, jint, jlong);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alGetSourcei
 * Signature: (IILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alGetSourcei__IILjava_nio_Buffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alGetSourcei
 * Signature: (IIJ)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alGetSourcei__IIJ
  (JNIEnv *, jclass, jint, jint, jlong);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alGetSource3i
 * Signature: (IILjava/nio/Buffer;ILjava/nio/Buffer;ILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alGetSource3i__IILjava_nio_Buffer_2ILjava_nio_Buffer_2ILjava_nio_Buffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint, jobject, jint, jobject, jint);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alGetSource3i
 * Signature: (IIJJJ)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alGetSource3i__IIJJJ
  (JNIEnv *, jclass, jint, jint, jlong, jlong, jlong);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alGetSourceiv
 * Signature: (IILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alGetSourceiv__IILjava_nio_Buffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alGetSourceiv
 * Signature: (IIJ)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alGetSourceiv__IIJ
  (JNIEnv *, jclass, jint, jint, jlong);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alSourcePlayv
 * Signature: (ILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alSourcePlayv__ILjava_nio_Buffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alSourcePlayv
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alSourcePlayv__IJ
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alSourceStopv
 * Signature: (ILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alSourceStopv__ILjava_nio_Buffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alSourceStopv
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alSourceStopv__IJ
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alSourceRewindv
 * Signature: (ILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alSourceRewindv__ILjava_nio_Buffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alSourceRewindv
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alSourceRewindv__IJ
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alSourcePausev
 * Signature: (ILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alSourcePausev__ILjava_nio_Buffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alSourcePausev
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alSourcePausev__IJ
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alSourcePlay
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alSourcePlay
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alSourceStop
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alSourceStop
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alSourceRewind
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alSourceRewind
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alSourcePause
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alSourcePause
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alSourceQueueBuffers
 * Signature: (IILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alSourceQueueBuffers__IILjava_nio_Buffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alSourceQueueBuffers
 * Signature: (IIJ)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alSourceQueueBuffers__IIJ
  (JNIEnv *, jclass, jint, jint, jlong);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alSourceUnqueueBuffers
 * Signature: (IILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alSourceUnqueueBuffers__IILjava_nio_Buffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alSourceUnqueueBuffers
 * Signature: (IIJ)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alSourceUnqueueBuffers__IIJ
  (JNIEnv *, jclass, jint, jint, jlong);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alGenBuffers
 * Signature: (ILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alGenBuffers__ILjava_nio_Buffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alGenBuffers
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alGenBuffers__IJ
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alDeleteBuffers
 * Signature: (ILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alDeleteBuffers__ILjava_nio_Buffer_2I
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alDeleteBuffers
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alDeleteBuffers__IJ
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alIsBuffer
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_badlogic_jglfw_al_AL_alIsBuffer
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alBufferData
 * Signature: (IILjava/nio/Buffer;III)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alBufferData__IILjava_nio_Buffer_2III
  (JNIEnv *, jclass, jint, jint, jobject, jint, jint, jint);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alBufferData
 * Signature: (IIJII)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alBufferData__IIJII
  (JNIEnv *, jclass, jint, jint, jlong, jint, jint);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alBufferf
 * Signature: (IIF)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alBufferf
  (JNIEnv *, jclass, jint, jint, jfloat);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alBuffer3f
 * Signature: (IIFFF)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alBuffer3f
  (JNIEnv *, jclass, jint, jint, jfloat, jfloat, jfloat);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alBufferfv
 * Signature: (IILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alBufferfv__IILjava_nio_Buffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alBufferfv
 * Signature: (IIJ)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alBufferfv__IIJ
  (JNIEnv *, jclass, jint, jint, jlong);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alBufferi
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alBufferi
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alBuffer3i
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alBuffer3i
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alBufferiv
 * Signature: (IILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alBufferiv__IILjava_nio_Buffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alBufferiv
 * Signature: (IIJ)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alBufferiv__IIJ
  (JNIEnv *, jclass, jint, jint, jlong);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alGetBufferf
 * Signature: (IILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alGetBufferf__IILjava_nio_Buffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alGetBufferf
 * Signature: (IIJ)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alGetBufferf__IIJ
  (JNIEnv *, jclass, jint, jint, jlong);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alGetBuffer3f
 * Signature: (IILjava/nio/Buffer;ILjava/nio/Buffer;ILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alGetBuffer3f__IILjava_nio_Buffer_2ILjava_nio_Buffer_2ILjava_nio_Buffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint, jobject, jint, jobject, jint);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alGetBuffer3f
 * Signature: (IIJJJ)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alGetBuffer3f__IIJJJ
  (JNIEnv *, jclass, jint, jint, jlong, jlong, jlong);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alGetBufferfv
 * Signature: (IILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alGetBufferfv__IILjava_nio_Buffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alGetBufferfv
 * Signature: (IIJ)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alGetBufferfv__IIJ
  (JNIEnv *, jclass, jint, jint, jlong);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alGetBufferi
 * Signature: (IILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alGetBufferi__IILjava_nio_Buffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alGetBufferi
 * Signature: (IIJ)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alGetBufferi__IIJ
  (JNIEnv *, jclass, jint, jint, jlong);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alGetBuffer3i
 * Signature: (IILjava/nio/Buffer;ILjava/nio/Buffer;ILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alGetBuffer3i__IILjava_nio_Buffer_2ILjava_nio_Buffer_2ILjava_nio_Buffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint, jobject, jint, jobject, jint);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alGetBuffer3i
 * Signature: (IIJJJ)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alGetBuffer3i__IIJJJ
  (JNIEnv *, jclass, jint, jint, jlong, jlong, jlong);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alGetBufferiv
 * Signature: (IILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alGetBufferiv__IILjava_nio_Buffer_2I
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     com_badlogic_jglfw_al_AL
 * Method:    alGetBufferiv
 * Signature: (IIJ)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_al_AL_alGetBufferiv__IIJ
  (JNIEnv *, jclass, jint, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
