/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_badlogic_jglfw_Glfw */

#ifndef _Included_com_badlogic_jglfw_Glfw
#define _Included_com_badlogic_jglfw_Glfw
#ifdef __cplusplus
extern "C" {
#endif
#undef com_badlogic_jglfw_Glfw_GLFW_VERSION_MAJOR
#define com_badlogic_jglfw_Glfw_GLFW_VERSION_MAJOR 3L
#undef com_badlogic_jglfw_Glfw_GLFW_VERSION_MINOR
#define com_badlogic_jglfw_Glfw_GLFW_VERSION_MINOR 0L
#undef com_badlogic_jglfw_Glfw_GLFW_VERSION_REVISION
#define com_badlogic_jglfw_Glfw_GLFW_VERSION_REVISION 0L
#undef com_badlogic_jglfw_Glfw_GLFW_RELEASE
#define com_badlogic_jglfw_Glfw_GLFW_RELEASE 0L
#undef com_badlogic_jglfw_Glfw_GLFW_PRESS
#define com_badlogic_jglfw_Glfw_GLFW_PRESS 1L
#undef com_badlogic_jglfw_Glfw_GLFW_REPEAT
#define com_badlogic_jglfw_Glfw_GLFW_REPEAT 2L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_SPACE
#define com_badlogic_jglfw_Glfw_GLFW_KEY_SPACE 32L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_APOSTROPHE
#define com_badlogic_jglfw_Glfw_GLFW_KEY_APOSTROPHE 39L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_COMMA
#define com_badlogic_jglfw_Glfw_GLFW_KEY_COMMA 44L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_MINUS
#define com_badlogic_jglfw_Glfw_GLFW_KEY_MINUS 45L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_PERIOD
#define com_badlogic_jglfw_Glfw_GLFW_KEY_PERIOD 46L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_SLASH
#define com_badlogic_jglfw_Glfw_GLFW_KEY_SLASH 47L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_0
#define com_badlogic_jglfw_Glfw_GLFW_KEY_0 48L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_1
#define com_badlogic_jglfw_Glfw_GLFW_KEY_1 49L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_2
#define com_badlogic_jglfw_Glfw_GLFW_KEY_2 50L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_3
#define com_badlogic_jglfw_Glfw_GLFW_KEY_3 51L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_4
#define com_badlogic_jglfw_Glfw_GLFW_KEY_4 52L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_5
#define com_badlogic_jglfw_Glfw_GLFW_KEY_5 53L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_6
#define com_badlogic_jglfw_Glfw_GLFW_KEY_6 54L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_7
#define com_badlogic_jglfw_Glfw_GLFW_KEY_7 55L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_8
#define com_badlogic_jglfw_Glfw_GLFW_KEY_8 56L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_9
#define com_badlogic_jglfw_Glfw_GLFW_KEY_9 57L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_SEMICOLON
#define com_badlogic_jglfw_Glfw_GLFW_KEY_SEMICOLON 59L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_EQUAL
#define com_badlogic_jglfw_Glfw_GLFW_KEY_EQUAL 61L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_A
#define com_badlogic_jglfw_Glfw_GLFW_KEY_A 65L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_B
#define com_badlogic_jglfw_Glfw_GLFW_KEY_B 66L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_C
#define com_badlogic_jglfw_Glfw_GLFW_KEY_C 67L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_D
#define com_badlogic_jglfw_Glfw_GLFW_KEY_D 68L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_E
#define com_badlogic_jglfw_Glfw_GLFW_KEY_E 69L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_F
#define com_badlogic_jglfw_Glfw_GLFW_KEY_F 70L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_G
#define com_badlogic_jglfw_Glfw_GLFW_KEY_G 71L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_H
#define com_badlogic_jglfw_Glfw_GLFW_KEY_H 72L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_I
#define com_badlogic_jglfw_Glfw_GLFW_KEY_I 73L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_J
#define com_badlogic_jglfw_Glfw_GLFW_KEY_J 74L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_K
#define com_badlogic_jglfw_Glfw_GLFW_KEY_K 75L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_L
#define com_badlogic_jglfw_Glfw_GLFW_KEY_L 76L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_M
#define com_badlogic_jglfw_Glfw_GLFW_KEY_M 77L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_N
#define com_badlogic_jglfw_Glfw_GLFW_KEY_N 78L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_O
#define com_badlogic_jglfw_Glfw_GLFW_KEY_O 79L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_P
#define com_badlogic_jglfw_Glfw_GLFW_KEY_P 80L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_Q
#define com_badlogic_jglfw_Glfw_GLFW_KEY_Q 81L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_R
#define com_badlogic_jglfw_Glfw_GLFW_KEY_R 82L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_S
#define com_badlogic_jglfw_Glfw_GLFW_KEY_S 83L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_T
#define com_badlogic_jglfw_Glfw_GLFW_KEY_T 84L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_U
#define com_badlogic_jglfw_Glfw_GLFW_KEY_U 85L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_V
#define com_badlogic_jglfw_Glfw_GLFW_KEY_V 86L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_W
#define com_badlogic_jglfw_Glfw_GLFW_KEY_W 87L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_X
#define com_badlogic_jglfw_Glfw_GLFW_KEY_X 88L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_Y
#define com_badlogic_jglfw_Glfw_GLFW_KEY_Y 89L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_Z
#define com_badlogic_jglfw_Glfw_GLFW_KEY_Z 90L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_LEFT_BRACKET
#define com_badlogic_jglfw_Glfw_GLFW_KEY_LEFT_BRACKET 91L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_BACKSLASH
#define com_badlogic_jglfw_Glfw_GLFW_KEY_BACKSLASH 92L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_RIGHT_BRACKET
#define com_badlogic_jglfw_Glfw_GLFW_KEY_RIGHT_BRACKET 93L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_GRAVE_ACCENT
#define com_badlogic_jglfw_Glfw_GLFW_KEY_GRAVE_ACCENT 96L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_WORLD_1
#define com_badlogic_jglfw_Glfw_GLFW_KEY_WORLD_1 161L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_WORLD_2
#define com_badlogic_jglfw_Glfw_GLFW_KEY_WORLD_2 162L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_ESCAPE
#define com_badlogic_jglfw_Glfw_GLFW_KEY_ESCAPE 256L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_ENTER
#define com_badlogic_jglfw_Glfw_GLFW_KEY_ENTER 257L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_TAB
#define com_badlogic_jglfw_Glfw_GLFW_KEY_TAB 258L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_BACKSPACE
#define com_badlogic_jglfw_Glfw_GLFW_KEY_BACKSPACE 259L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_INSERT
#define com_badlogic_jglfw_Glfw_GLFW_KEY_INSERT 260L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_DELETE
#define com_badlogic_jglfw_Glfw_GLFW_KEY_DELETE 261L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_RIGHT
#define com_badlogic_jglfw_Glfw_GLFW_KEY_RIGHT 262L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_LEFT
#define com_badlogic_jglfw_Glfw_GLFW_KEY_LEFT 263L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_DOWN
#define com_badlogic_jglfw_Glfw_GLFW_KEY_DOWN 264L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_UP
#define com_badlogic_jglfw_Glfw_GLFW_KEY_UP 265L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_PAGE_UP
#define com_badlogic_jglfw_Glfw_GLFW_KEY_PAGE_UP 266L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_PAGE_DOWN
#define com_badlogic_jglfw_Glfw_GLFW_KEY_PAGE_DOWN 267L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_HOME
#define com_badlogic_jglfw_Glfw_GLFW_KEY_HOME 268L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_END
#define com_badlogic_jglfw_Glfw_GLFW_KEY_END 269L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_CAPS_LOCK
#define com_badlogic_jglfw_Glfw_GLFW_KEY_CAPS_LOCK 280L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_SCROLL_LOCK
#define com_badlogic_jglfw_Glfw_GLFW_KEY_SCROLL_LOCK 281L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_NUM_LOCK
#define com_badlogic_jglfw_Glfw_GLFW_KEY_NUM_LOCK 282L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_PRINT_SCREEN
#define com_badlogic_jglfw_Glfw_GLFW_KEY_PRINT_SCREEN 283L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_PAUSE
#define com_badlogic_jglfw_Glfw_GLFW_KEY_PAUSE 284L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_F1
#define com_badlogic_jglfw_Glfw_GLFW_KEY_F1 290L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_F2
#define com_badlogic_jglfw_Glfw_GLFW_KEY_F2 291L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_F3
#define com_badlogic_jglfw_Glfw_GLFW_KEY_F3 292L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_F4
#define com_badlogic_jglfw_Glfw_GLFW_KEY_F4 293L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_F5
#define com_badlogic_jglfw_Glfw_GLFW_KEY_F5 294L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_F6
#define com_badlogic_jglfw_Glfw_GLFW_KEY_F6 295L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_F7
#define com_badlogic_jglfw_Glfw_GLFW_KEY_F7 296L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_F8
#define com_badlogic_jglfw_Glfw_GLFW_KEY_F8 297L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_F9
#define com_badlogic_jglfw_Glfw_GLFW_KEY_F9 298L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_F10
#define com_badlogic_jglfw_Glfw_GLFW_KEY_F10 299L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_F11
#define com_badlogic_jglfw_Glfw_GLFW_KEY_F11 300L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_F12
#define com_badlogic_jglfw_Glfw_GLFW_KEY_F12 301L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_F13
#define com_badlogic_jglfw_Glfw_GLFW_KEY_F13 302L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_F14
#define com_badlogic_jglfw_Glfw_GLFW_KEY_F14 303L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_F15
#define com_badlogic_jglfw_Glfw_GLFW_KEY_F15 304L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_F16
#define com_badlogic_jglfw_Glfw_GLFW_KEY_F16 305L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_F17
#define com_badlogic_jglfw_Glfw_GLFW_KEY_F17 306L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_F18
#define com_badlogic_jglfw_Glfw_GLFW_KEY_F18 307L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_F19
#define com_badlogic_jglfw_Glfw_GLFW_KEY_F19 308L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_F20
#define com_badlogic_jglfw_Glfw_GLFW_KEY_F20 309L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_F21
#define com_badlogic_jglfw_Glfw_GLFW_KEY_F21 310L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_F22
#define com_badlogic_jglfw_Glfw_GLFW_KEY_F22 311L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_F23
#define com_badlogic_jglfw_Glfw_GLFW_KEY_F23 312L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_F24
#define com_badlogic_jglfw_Glfw_GLFW_KEY_F24 313L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_F25
#define com_badlogic_jglfw_Glfw_GLFW_KEY_F25 314L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_KP_0
#define com_badlogic_jglfw_Glfw_GLFW_KEY_KP_0 320L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_KP_1
#define com_badlogic_jglfw_Glfw_GLFW_KEY_KP_1 321L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_KP_2
#define com_badlogic_jglfw_Glfw_GLFW_KEY_KP_2 322L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_KP_3
#define com_badlogic_jglfw_Glfw_GLFW_KEY_KP_3 323L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_KP_4
#define com_badlogic_jglfw_Glfw_GLFW_KEY_KP_4 324L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_KP_5
#define com_badlogic_jglfw_Glfw_GLFW_KEY_KP_5 325L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_KP_6
#define com_badlogic_jglfw_Glfw_GLFW_KEY_KP_6 326L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_KP_7
#define com_badlogic_jglfw_Glfw_GLFW_KEY_KP_7 327L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_KP_8
#define com_badlogic_jglfw_Glfw_GLFW_KEY_KP_8 328L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_KP_9
#define com_badlogic_jglfw_Glfw_GLFW_KEY_KP_9 329L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_KP_DECIMAL
#define com_badlogic_jglfw_Glfw_GLFW_KEY_KP_DECIMAL 330L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_KP_DIVIDE
#define com_badlogic_jglfw_Glfw_GLFW_KEY_KP_DIVIDE 331L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_KP_MULTIPLY
#define com_badlogic_jglfw_Glfw_GLFW_KEY_KP_MULTIPLY 332L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_KP_SUBTRACT
#define com_badlogic_jglfw_Glfw_GLFW_KEY_KP_SUBTRACT 333L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_KP_ADD
#define com_badlogic_jglfw_Glfw_GLFW_KEY_KP_ADD 334L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_KP_ENTER
#define com_badlogic_jglfw_Glfw_GLFW_KEY_KP_ENTER 335L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_KP_EQUAL
#define com_badlogic_jglfw_Glfw_GLFW_KEY_KP_EQUAL 336L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_LEFT_SHIFT
#define com_badlogic_jglfw_Glfw_GLFW_KEY_LEFT_SHIFT 340L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_LEFT_CONTROL
#define com_badlogic_jglfw_Glfw_GLFW_KEY_LEFT_CONTROL 341L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_LEFT_ALT
#define com_badlogic_jglfw_Glfw_GLFW_KEY_LEFT_ALT 342L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_LEFT_SUPER
#define com_badlogic_jglfw_Glfw_GLFW_KEY_LEFT_SUPER 343L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_RIGHT_SHIFT
#define com_badlogic_jglfw_Glfw_GLFW_KEY_RIGHT_SHIFT 344L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_RIGHT_CONTROL
#define com_badlogic_jglfw_Glfw_GLFW_KEY_RIGHT_CONTROL 345L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_RIGHT_ALT
#define com_badlogic_jglfw_Glfw_GLFW_KEY_RIGHT_ALT 346L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_RIGHT_SUPER
#define com_badlogic_jglfw_Glfw_GLFW_KEY_RIGHT_SUPER 347L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_MENU
#define com_badlogic_jglfw_Glfw_GLFW_KEY_MENU 348L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_LAST
#define com_badlogic_jglfw_Glfw_GLFW_KEY_LAST 348L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_ESC
#define com_badlogic_jglfw_Glfw_GLFW_KEY_ESC 256L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_DEL
#define com_badlogic_jglfw_Glfw_GLFW_KEY_DEL 261L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_PAGEUP
#define com_badlogic_jglfw_Glfw_GLFW_KEY_PAGEUP 266L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_PAGEDOWN
#define com_badlogic_jglfw_Glfw_GLFW_KEY_PAGEDOWN 267L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_KP_NUM_LOCK
#define com_badlogic_jglfw_Glfw_GLFW_KEY_KP_NUM_LOCK 282L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_LCTRL
#define com_badlogic_jglfw_Glfw_GLFW_KEY_LCTRL 341L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_LSHIFT
#define com_badlogic_jglfw_Glfw_GLFW_KEY_LSHIFT 340L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_LALT
#define com_badlogic_jglfw_Glfw_GLFW_KEY_LALT 342L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_LSUPER
#define com_badlogic_jglfw_Glfw_GLFW_KEY_LSUPER 343L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_RCTRL
#define com_badlogic_jglfw_Glfw_GLFW_KEY_RCTRL 345L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_RSHIFT
#define com_badlogic_jglfw_Glfw_GLFW_KEY_RSHIFT 344L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_RALT
#define com_badlogic_jglfw_Glfw_GLFW_KEY_RALT 346L
#undef com_badlogic_jglfw_Glfw_GLFW_KEY_RSUPER
#define com_badlogic_jglfw_Glfw_GLFW_KEY_RSUPER 347L
#undef com_badlogic_jglfw_Glfw_GLFW_MOUSE_BUTTON_1
#define com_badlogic_jglfw_Glfw_GLFW_MOUSE_BUTTON_1 0L
#undef com_badlogic_jglfw_Glfw_GLFW_MOUSE_BUTTON_2
#define com_badlogic_jglfw_Glfw_GLFW_MOUSE_BUTTON_2 1L
#undef com_badlogic_jglfw_Glfw_GLFW_MOUSE_BUTTON_3
#define com_badlogic_jglfw_Glfw_GLFW_MOUSE_BUTTON_3 2L
#undef com_badlogic_jglfw_Glfw_GLFW_MOUSE_BUTTON_4
#define com_badlogic_jglfw_Glfw_GLFW_MOUSE_BUTTON_4 3L
#undef com_badlogic_jglfw_Glfw_GLFW_MOUSE_BUTTON_5
#define com_badlogic_jglfw_Glfw_GLFW_MOUSE_BUTTON_5 4L
#undef com_badlogic_jglfw_Glfw_GLFW_MOUSE_BUTTON_6
#define com_badlogic_jglfw_Glfw_GLFW_MOUSE_BUTTON_6 5L
#undef com_badlogic_jglfw_Glfw_GLFW_MOUSE_BUTTON_7
#define com_badlogic_jglfw_Glfw_GLFW_MOUSE_BUTTON_7 6L
#undef com_badlogic_jglfw_Glfw_GLFW_MOUSE_BUTTON_8
#define com_badlogic_jglfw_Glfw_GLFW_MOUSE_BUTTON_8 7L
#undef com_badlogic_jglfw_Glfw_GLFW_MOUSE_BUTTON_LAST
#define com_badlogic_jglfw_Glfw_GLFW_MOUSE_BUTTON_LAST 7L
#undef com_badlogic_jglfw_Glfw_GLFW_MOUSE_BUTTON_LEFT
#define com_badlogic_jglfw_Glfw_GLFW_MOUSE_BUTTON_LEFT 0L
#undef com_badlogic_jglfw_Glfw_GLFW_MOUSE_BUTTON_RIGHT
#define com_badlogic_jglfw_Glfw_GLFW_MOUSE_BUTTON_RIGHT 1L
#undef com_badlogic_jglfw_Glfw_GLFW_MOUSE_BUTTON_MIDDLE
#define com_badlogic_jglfw_Glfw_GLFW_MOUSE_BUTTON_MIDDLE 2L
#undef com_badlogic_jglfw_Glfw_GLFW_JOYSTICK_1
#define com_badlogic_jglfw_Glfw_GLFW_JOYSTICK_1 0L
#undef com_badlogic_jglfw_Glfw_GLFW_JOYSTICK_2
#define com_badlogic_jglfw_Glfw_GLFW_JOYSTICK_2 1L
#undef com_badlogic_jglfw_Glfw_GLFW_JOYSTICK_3
#define com_badlogic_jglfw_Glfw_GLFW_JOYSTICK_3 2L
#undef com_badlogic_jglfw_Glfw_GLFW_JOYSTICK_4
#define com_badlogic_jglfw_Glfw_GLFW_JOYSTICK_4 3L
#undef com_badlogic_jglfw_Glfw_GLFW_JOYSTICK_5
#define com_badlogic_jglfw_Glfw_GLFW_JOYSTICK_5 4L
#undef com_badlogic_jglfw_Glfw_GLFW_JOYSTICK_6
#define com_badlogic_jglfw_Glfw_GLFW_JOYSTICK_6 5L
#undef com_badlogic_jglfw_Glfw_GLFW_JOYSTICK_7
#define com_badlogic_jglfw_Glfw_GLFW_JOYSTICK_7 6L
#undef com_badlogic_jglfw_Glfw_GLFW_JOYSTICK_8
#define com_badlogic_jglfw_Glfw_GLFW_JOYSTICK_8 7L
#undef com_badlogic_jglfw_Glfw_GLFW_JOYSTICK_9
#define com_badlogic_jglfw_Glfw_GLFW_JOYSTICK_9 8L
#undef com_badlogic_jglfw_Glfw_GLFW_JOYSTICK_10
#define com_badlogic_jglfw_Glfw_GLFW_JOYSTICK_10 9L
#undef com_badlogic_jglfw_Glfw_GLFW_JOYSTICK_11
#define com_badlogic_jglfw_Glfw_GLFW_JOYSTICK_11 10L
#undef com_badlogic_jglfw_Glfw_GLFW_JOYSTICK_12
#define com_badlogic_jglfw_Glfw_GLFW_JOYSTICK_12 11L
#undef com_badlogic_jglfw_Glfw_GLFW_JOYSTICK_13
#define com_badlogic_jglfw_Glfw_GLFW_JOYSTICK_13 12L
#undef com_badlogic_jglfw_Glfw_GLFW_JOYSTICK_14
#define com_badlogic_jglfw_Glfw_GLFW_JOYSTICK_14 13L
#undef com_badlogic_jglfw_Glfw_GLFW_JOYSTICK_15
#define com_badlogic_jglfw_Glfw_GLFW_JOYSTICK_15 14L
#undef com_badlogic_jglfw_Glfw_GLFW_JOYSTICK_16
#define com_badlogic_jglfw_Glfw_GLFW_JOYSTICK_16 15L
#undef com_badlogic_jglfw_Glfw_GLFW_JOYSTICK_LAST
#define com_badlogic_jglfw_Glfw_GLFW_JOYSTICK_LAST 15L
#undef com_badlogic_jglfw_Glfw_GLFW_NO_ERROR
#define com_badlogic_jglfw_Glfw_GLFW_NO_ERROR 0L
#undef com_badlogic_jglfw_Glfw_GLFW_NOT_INITIALIZED
#define com_badlogic_jglfw_Glfw_GLFW_NOT_INITIALIZED 458753L
#undef com_badlogic_jglfw_Glfw_GLFW_NO_CURRENT_CONTEXT
#define com_badlogic_jglfw_Glfw_GLFW_NO_CURRENT_CONTEXT 458754L
#undef com_badlogic_jglfw_Glfw_GLFW_INVALID_ENUM
#define com_badlogic_jglfw_Glfw_GLFW_INVALID_ENUM 458755L
#undef com_badlogic_jglfw_Glfw_GLFW_INVALID_VALUE
#define com_badlogic_jglfw_Glfw_GLFW_INVALID_VALUE 458756L
#undef com_badlogic_jglfw_Glfw_GLFW_OUT_OF_MEMORY
#define com_badlogic_jglfw_Glfw_GLFW_OUT_OF_MEMORY 458757L
#undef com_badlogic_jglfw_Glfw_GLFW_API_UNAVAILABLE
#define com_badlogic_jglfw_Glfw_GLFW_API_UNAVAILABLE 458758L
#undef com_badlogic_jglfw_Glfw_GLFW_VERSION_UNAVAILABLE
#define com_badlogic_jglfw_Glfw_GLFW_VERSION_UNAVAILABLE 458759L
#undef com_badlogic_jglfw_Glfw_GLFW_PLATFORM_ERROR
#define com_badlogic_jglfw_Glfw_GLFW_PLATFORM_ERROR 458760L
#undef com_badlogic_jglfw_Glfw_GLFW_FORMAT_UNAVAILABLE
#define com_badlogic_jglfw_Glfw_GLFW_FORMAT_UNAVAILABLE 458761L
#undef com_badlogic_jglfw_Glfw_GLFW_FOCUSED
#define com_badlogic_jglfw_Glfw_GLFW_FOCUSED 131073L
#undef com_badlogic_jglfw_Glfw_GLFW_ICONIFIED
#define com_badlogic_jglfw_Glfw_GLFW_ICONIFIED 131074L
#undef com_badlogic_jglfw_Glfw_GLFW_RESIZABLE
#define com_badlogic_jglfw_Glfw_GLFW_RESIZABLE 139271L
#undef com_badlogic_jglfw_Glfw_GLFW_VISIBLE
#define com_badlogic_jglfw_Glfw_GLFW_VISIBLE 139272L
#undef com_badlogic_jglfw_Glfw_GLFW_UNDECORATED
#define com_badlogic_jglfw_Glfw_GLFW_UNDECORATED 139273L
#undef com_badlogic_jglfw_Glfw_GLFW_CONTEXT_REVISION
#define com_badlogic_jglfw_Glfw_GLFW_CONTEXT_REVISION 131076L
#undef com_badlogic_jglfw_Glfw_GLFW_RED_BITS
#define com_badlogic_jglfw_Glfw_GLFW_RED_BITS 135168L
#undef com_badlogic_jglfw_Glfw_GLFW_GREEN_BITS
#define com_badlogic_jglfw_Glfw_GLFW_GREEN_BITS 135169L
#undef com_badlogic_jglfw_Glfw_GLFW_BLUE_BITS
#define com_badlogic_jglfw_Glfw_GLFW_BLUE_BITS 135170L
#undef com_badlogic_jglfw_Glfw_GLFW_ALPHA_BITS
#define com_badlogic_jglfw_Glfw_GLFW_ALPHA_BITS 135171L
#undef com_badlogic_jglfw_Glfw_GLFW_DEPTH_BITS
#define com_badlogic_jglfw_Glfw_GLFW_DEPTH_BITS 135172L
#undef com_badlogic_jglfw_Glfw_GLFW_STENCIL_BITS
#define com_badlogic_jglfw_Glfw_GLFW_STENCIL_BITS 135173L
#undef com_badlogic_jglfw_Glfw_GLFW_ACCUM_RED_BITS
#define com_badlogic_jglfw_Glfw_GLFW_ACCUM_RED_BITS 135174L
#undef com_badlogic_jglfw_Glfw_GLFW_ACCUM_GREEN_BITS
#define com_badlogic_jglfw_Glfw_GLFW_ACCUM_GREEN_BITS 135175L
#undef com_badlogic_jglfw_Glfw_GLFW_ACCUM_BLUE_BITS
#define com_badlogic_jglfw_Glfw_GLFW_ACCUM_BLUE_BITS 135176L
#undef com_badlogic_jglfw_Glfw_GLFW_ACCUM_ALPHA_BITS
#define com_badlogic_jglfw_Glfw_GLFW_ACCUM_ALPHA_BITS 135177L
#undef com_badlogic_jglfw_Glfw_GLFW_AUX_BUFFERS
#define com_badlogic_jglfw_Glfw_GLFW_AUX_BUFFERS 135178L
#undef com_badlogic_jglfw_Glfw_GLFW_STEREO
#define com_badlogic_jglfw_Glfw_GLFW_STEREO 135179L
#undef com_badlogic_jglfw_Glfw_GLFW_SAMPLES
#define com_badlogic_jglfw_Glfw_GLFW_SAMPLES 135180L
#undef com_badlogic_jglfw_Glfw_GLFW_SRGB_CAPABLE
#define com_badlogic_jglfw_Glfw_GLFW_SRGB_CAPABLE 135181L
#undef com_badlogic_jglfw_Glfw_GLFW_CLIENT_API
#define com_badlogic_jglfw_Glfw_GLFW_CLIENT_API 139264L
#undef com_badlogic_jglfw_Glfw_GLFW_CONTEXT_VERSION_MAJOR
#define com_badlogic_jglfw_Glfw_GLFW_CONTEXT_VERSION_MAJOR 139265L
#undef com_badlogic_jglfw_Glfw_GLFW_CONTEXT_VERSION_MINOR
#define com_badlogic_jglfw_Glfw_GLFW_CONTEXT_VERSION_MINOR 139266L
#undef com_badlogic_jglfw_Glfw_GLFW_CONTEXT_ROBUSTNESS
#define com_badlogic_jglfw_Glfw_GLFW_CONTEXT_ROBUSTNESS 139267L
#undef com_badlogic_jglfw_Glfw_GLFW_OPENGL_FORWARD_COMPAT
#define com_badlogic_jglfw_Glfw_GLFW_OPENGL_FORWARD_COMPAT 139268L
#undef com_badlogic_jglfw_Glfw_GLFW_OPENGL_DEBUG_CONTEXT
#define com_badlogic_jglfw_Glfw_GLFW_OPENGL_DEBUG_CONTEXT 139269L
#undef com_badlogic_jglfw_Glfw_GLFW_OPENGL_PROFILE
#define com_badlogic_jglfw_Glfw_GLFW_OPENGL_PROFILE 139270L
#undef com_badlogic_jglfw_Glfw_GLFW_OPENGL_API
#define com_badlogic_jglfw_Glfw_GLFW_OPENGL_API 1L
#undef com_badlogic_jglfw_Glfw_GLFW_OPENGL_ES_API
#define com_badlogic_jglfw_Glfw_GLFW_OPENGL_ES_API 2L
#undef com_badlogic_jglfw_Glfw_GLFW_NO_ROBUSTNESS
#define com_badlogic_jglfw_Glfw_GLFW_NO_ROBUSTNESS 0L
#undef com_badlogic_jglfw_Glfw_GLFW_NO_RESET_NOTIFICATION
#define com_badlogic_jglfw_Glfw_GLFW_NO_RESET_NOTIFICATION 1L
#undef com_badlogic_jglfw_Glfw_GLFW_LOSE_CONTEXT_ON_RESET
#define com_badlogic_jglfw_Glfw_GLFW_LOSE_CONTEXT_ON_RESET 2L
#undef com_badlogic_jglfw_Glfw_GLFW_OPENGL_NO_PROFILE
#define com_badlogic_jglfw_Glfw_GLFW_OPENGL_NO_PROFILE 0L
#undef com_badlogic_jglfw_Glfw_GLFW_OPENGL_CORE_PROFILE
#define com_badlogic_jglfw_Glfw_GLFW_OPENGL_CORE_PROFILE 1L
#undef com_badlogic_jglfw_Glfw_GLFW_OPENGL_COMPAT_PROFILE
#define com_badlogic_jglfw_Glfw_GLFW_OPENGL_COMPAT_PROFILE 2L
#undef com_badlogic_jglfw_Glfw_GLFW_CURSOR_MODE
#define com_badlogic_jglfw_Glfw_GLFW_CURSOR_MODE 196609L
#undef com_badlogic_jglfw_Glfw_GLFW_STICKY_KEYS
#define com_badlogic_jglfw_Glfw_GLFW_STICKY_KEYS 196610L
#undef com_badlogic_jglfw_Glfw_GLFW_STICKY_MOUSE_BUTTONS
#define com_badlogic_jglfw_Glfw_GLFW_STICKY_MOUSE_BUTTONS 196611L
#undef com_badlogic_jglfw_Glfw_GLFW_CURSOR_NORMAL
#define com_badlogic_jglfw_Glfw_GLFW_CURSOR_NORMAL 262145L
#undef com_badlogic_jglfw_Glfw_GLFW_CURSOR_HIDDEN
#define com_badlogic_jglfw_Glfw_GLFW_CURSOR_HIDDEN 262146L
#undef com_badlogic_jglfw_Glfw_GLFW_CURSOR_CAPTURED
#define com_badlogic_jglfw_Glfw_GLFW_CURSOR_CAPTURED 262147L
#undef com_badlogic_jglfw_Glfw_GLFW_PRESENT
#define com_badlogic_jglfw_Glfw_GLFW_PRESENT 327681L
#undef com_badlogic_jglfw_Glfw_GLFW_AXES
#define com_badlogic_jglfw_Glfw_GLFW_AXES 327682L
#undef com_badlogic_jglfw_Glfw_GLFW_BUTTONS
#define com_badlogic_jglfw_Glfw_GLFW_BUTTONS 327683L
#undef com_badlogic_jglfw_Glfw_GLFW_GAMMA_RAMP_SIZE
#define com_badlogic_jglfw_Glfw_GLFW_GAMMA_RAMP_SIZE 256L
#undef com_badlogic_jglfw_Glfw_GLFW_CONNECTED
#define com_badlogic_jglfw_Glfw_GLFW_CONNECTED 397312L
#undef com_badlogic_jglfw_Glfw_GLFW_DISCONNECTED
#define com_badlogic_jglfw_Glfw_GLFW_DISCONNECTED 397313L
/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwInitJni
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_badlogic_jglfw_Glfw_glfwInitJni
  (JNIEnv *, jclass);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwTerminate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_Glfw_glfwTerminate
  (JNIEnv *, jclass);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwGetVersionString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_badlogic_jglfw_Glfw_glfwGetVersionString
  (JNIEnv *, jclass);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwGetMonitorsJni
 * Signature: ([J)I
 */
JNIEXPORT jint JNICALL Java_com_badlogic_jglfw_Glfw_glfwGetMonitorsJni
  (JNIEnv *, jclass, jlongArray);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwGetPrimaryMonitor
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_badlogic_jglfw_Glfw_glfwGetPrimaryMonitor
  (JNIEnv *, jclass);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwGetMonitorX
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_badlogic_jglfw_Glfw_glfwGetMonitorX
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwGetMonitorY
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_badlogic_jglfw_Glfw_glfwGetMonitorY
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwGetMonitorPhysicalWidth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_badlogic_jglfw_Glfw_glfwGetMonitorPhysicalWidth
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwGetMonitorPhysicalHeight
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_badlogic_jglfw_Glfw_glfwGetMonitorPhysicalHeight
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwGetMonitorName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_badlogic_jglfw_Glfw_glfwGetMonitorName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwGetVideoModesJni
 * Signature: (J[I)I
 */
JNIEXPORT jint JNICALL Java_com_badlogic_jglfw_Glfw_glfwGetVideoModesJni
  (JNIEnv *, jclass, jlong, jintArray);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwGetVideoModeJni
 * Signature: (J[I)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_Glfw_glfwGetVideoModeJni
  (JNIEnv *, jclass, jlong, jintArray);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwSetGamma
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_Glfw_glfwSetGamma
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwGetGammaRamp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_Glfw_glfwGetGammaRamp
  (JNIEnv *, jclass);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwSetGammaRamp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_Glfw_glfwSetGammaRamp
  (JNIEnv *, jclass);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwDefaultWindowHints
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_Glfw_glfwDefaultWindowHints
  (JNIEnv *, jclass);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwWindowHint
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_Glfw_glfwWindowHint
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwCreateWindowJni
 * Signature: (IILjava/lang/String;JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_badlogic_jglfw_Glfw_glfwCreateWindowJni
  (JNIEnv *, jclass, jint, jint, jstring, jlong, jlong);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwDestroyWindow
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_Glfw_glfwDestroyWindow
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwWindowShouldClose
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_badlogic_jglfw_Glfw_glfwWindowShouldClose
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwSetWindowShouldClose
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_Glfw_glfwSetWindowShouldClose
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwSetWindowTitle
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_Glfw_glfwSetWindowTitle
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwSetWindowPos
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_Glfw_glfwSetWindowPos
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwGetWindowX
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_badlogic_jglfw_Glfw_glfwGetWindowX
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwGetWindowY
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_badlogic_jglfw_Glfw_glfwGetWindowY
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwGetWindowWidth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_badlogic_jglfw_Glfw_glfwGetWindowWidth
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwGetWindowHeight
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_badlogic_jglfw_Glfw_glfwGetWindowHeight
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwSetWindowSize
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_Glfw_glfwSetWindowSize
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwIconifyWindow
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_Glfw_glfwIconifyWindow
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwRestoreWindow
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_Glfw_glfwRestoreWindow
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwHideWindow
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_Glfw_glfwHideWindow
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwShowWindow
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_Glfw_glfwShowWindow
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwGetWindowMonitor
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_badlogic_jglfw_Glfw_glfwGetWindowMonitor
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwGetWindowParam
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_badlogic_jglfw_Glfw_glfwGetWindowParam
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwSetCallbackJni
 * Signature: (Lcom/badlogic/jglfw/GlfwCallback;)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_Glfw_glfwSetCallbackJni
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwPollEventsJni
 * Signature: (Lcom/badlogic/jglfw/GlfwCallback;)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_Glfw_glfwPollEventsJni
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwWaitEventsJni
 * Signature: (Lcom/badlogic/jglfw/GlfwCallback;)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_Glfw_glfwWaitEventsJni
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwGetInputMode
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_badlogic_jglfw_Glfw_glfwGetInputMode
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwSetInputMode
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_Glfw_glfwSetInputMode
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwGetKey
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_badlogic_jglfw_Glfw_glfwGetKey
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwGetMouseButton
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_badlogic_jglfw_Glfw_glfwGetMouseButton
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwGetCursorPosX
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_badlogic_jglfw_Glfw_glfwGetCursorPosX
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwGetCursorPosY
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_badlogic_jglfw_Glfw_glfwGetCursorPosY
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwSetCursorPos
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_Glfw_glfwSetCursorPos
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwGetJoystickParam
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_badlogic_jglfw_Glfw_glfwGetJoystickParam
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwGetJoystickAxes
 * Signature: (I[F)I
 */
JNIEXPORT jint JNICALL Java_com_badlogic_jglfw_Glfw_glfwGetJoystickAxes
  (JNIEnv *, jclass, jint, jfloatArray);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwGetJoystickButtons
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_com_badlogic_jglfw_Glfw_glfwGetJoystickButtons
  (JNIEnv *, jclass, jint, jbyteArray);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwGetJoystickName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_badlogic_jglfw_Glfw_glfwGetJoystickName
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwSetClipboardString
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_Glfw_glfwSetClipboardString
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwGetClipboardString
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_badlogic_jglfw_Glfw_glfwGetClipboardString
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwGetTime
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_badlogic_jglfw_Glfw_glfwGetTime
  (JNIEnv *, jclass);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwSetTime
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_Glfw_glfwSetTime
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwMakeContextCurrentJni
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_Glfw_glfwMakeContextCurrentJni
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwGetCurrentContext
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_badlogic_jglfw_Glfw_glfwGetCurrentContext
  (JNIEnv *, jclass);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwSwapBuffers
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_Glfw_glfwSwapBuffers
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwSwapInterval
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_jglfw_Glfw_glfwSwapInterval
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_badlogic_jglfw_Glfw
 * Method:    glfwExtensionSupported
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_badlogic_jglfw_Glfw_glfwExtensionSupported
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
